package com.digital.telco.utility.exception;

public enum ErrorCodes {

	 INVENTORY_UPDATE_ERROR, INVALID_SOURCE_CODE, INVALID_CHANNEL_ERROR, DATE_PARSE_EXCEPTION, INVENTORY_FETCH_ERROR, SALES_ORDER_STATUS_UPDATE_ERROR,
	    INVALID_ORDER_STATUS_FETCH_ERROR, INVETORY_JSON_PARSE_EXCEPTION, INVALID_SOURCE_TYPE_ID, INVALID_SOURCE_ID, INVALID_CONFIGURATION, INVALID_SALES_ORDER, INVALID_BACKUP_SOURCE_ID, INVALID_SORT_KEY;
	
}
